config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "devise/user/sessions", registrations: "devise/user/registrations", passwords: "devise/user/passwords"}

  root 'user/pages#welcome'

  namespace :admin do
    root 'pages#dashboard'

    resources :backend_menus do
      collection do
        post 'ajax_update_position'
      end
    end
    resources :users do
      collection do
        post 'assign_role'
      end
    end
  end

  devise_scope :user do
    get "admin/sign_in" => "devise/admin/sessions#new"
    get "admin/sign_up" => "devise/admin/registrations#new"
    get "admin/password/new" => "devise/admin/passwords#new"
    get "admin/password/edit" => "devise/admin/passwords#edit"
  end

end

app/models/backend_menu.rb
# == Schema Information
#
# Table name: backend_menus
#
#  id            :integer          not null, primary key
#  parent_id     :integer
#  name          :string(255)
#  icon          :string(255)
#  url           :string(255)
#  highlight     :string(255)
#  display_order :integer
#  level         :integer
#  role          :string(255)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class BackendMenu < ActiveRecord::Base
	validates_uniqueness_of :name
end

app/controllers/admin/backend_menus_controller.rb
class Admin::BackendMenusController < AdminController
  before_action :set_backend_menu, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def index
    @backend_menus = BackendMenu.all.order(:display_order)
  end

  def new
    @backend_menu = BackendMenu.new
  end

  def edit
  end

  def create
    @backend_menu = BackendMenu.new(backend_menu_params)
    @backend_menu.level = backend_menu_params['parent_id'].blank? ? 0 : (BackendMenu.find(backend_menu_params['parent_id']).level + 1)
    respond_to do |format|
      if @backend_menu.save
        flash[:success] = 'Backend menu was successfully created.'
        format.html { redirect_to admin_backend_menus_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      @backend_menu.level = backend_menu_params['parent_id'].blank? ? 0 : (BackendMenu.find(backend_menu_params['parent_id']).level + 1)
      if @backend_menu.update(backend_menu_params)
        flash[:success] = 'Backend menu was successfully updated.'
        format.html { redirect_to admin_backend_menus_path  }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @backend_menu.destroy
    respond_to do |format|
      flash[:success] = 'Backend menu was successfully destroyed.'
      format.html { redirect_to admin_backend_menus_path }
    end
  end

  def ajax_update_position
    id_data = ActiveSupport::JSON.decode(params[:pid]).drop(1)
    id_data.each_with_index do |item , index|
      row = BackendMenu.find(item)
      row.display_order = index
      row.save
    end
    respond_to do |format|
      format.json{ render json: id_data}
    end
  end

  private
    def set_backend_menu
      @backend_menu = BackendMenu.find(params[:id])
    end

    def backend_menu_params
      params.require(:backend_menu).permit(:parent_id, :name, :icon, :highlight, :url, :display_order)
    end
end

app/views/admin/backend_menus/_form.html.erb
<%= form_for([:admin, @backend_menu], :html => {class: 'form-horizontal'}) do |f| %>
    <div class="form-group">
      <label for="description" class="col-sm-2 control-label"><%= f.label 'Parent menu' %></label>
      <div class="col-sm-8">
        <%= select("backend_menu", "parent_id", BackendMenu.where.not(id: params[:id])
            .where('parent_id IS NULL OR parent_id = ?', 0)
            .collect {|p| [ p.name, p.id ] }, {include_blank: 'Select Parent'}, class: 'form-control') %>
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label"><%= f.label :name %></label>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <label for="description" class="col-sm-2 control-label"><%= f.label :icon %></label>
      <div class="col-sm-8">
        <%= f.text_field :icon, class: 'form-control icon-picker' %>
      </div>
    </div>
    <div class="form-group">
      <label for="description" class="col-sm-2 control-label"><%= f.label :url %></label>
      <div class="col-sm-8">
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <label for="description" class="col-sm-2 control-label"><%= f.label :highlight %></label>
      <div class="col-sm-8">
        <% f.text_area :highlight, class: 'form-control' %>
        <%= f.text_area :highlight, class: 'form-control', :required => true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-8">
        <%= link_to 'Back', admin_backend_menus_path, :class => 'btn btn-default'%>
        <%= f.submit 'Submit', :class => "btn btn-primary"%>
      </div>
    </div>
<% end %>

<script>
  $(document).ready(function(){
    $('.icon-picker').iconpicker({
      placement:'bottomLeft'
    });
  })
</script>

app/views/admin/backend_menus/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa fa-cog fa-fw "></i>
      <%= 'System' %>
      <span>&gt;
        <%=  link_to 'List of backend menus', admin_backend_menus_path %>
          </span>
    </h1>
  </div>
</div>
<div class="row">
  <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

    <div class="jarviswidget jarviswidget-sortable jarviswidget-color-darken" id="wid-id-4" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">

      <header role="heading">
        <span class="widget-icon">
            <i class="fa fa-edit"></i>
        </span>
        <h2><%= 'Edit Backend Menu'%></h2>
      </header>

      <div role="content">
        <div class="widget-body">

          <%= render 'form' %>

        </div>
      </div>

    </div>
  </article>
</div>

app/views/admin/backend_menus/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-home"></i> System <span>> List of backend menus</span></h1>
  </div>
  <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
    <ul id="sparks" class="">
      <li class="sparks-info">
        <%= link_to 'Add new backend menu', new_admin_backend_menu_path, :class => 'btn btn-primary'%>
      </li>
    </ul>
  </div>
</div>
<div class="row">
  <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="true">
      <header>
        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
        <h2><%= 'List of backend menus' %></h2>
      </header>
      <div>
        <div class="jarviswidget-editbox"></div>

        <div class="widget-body">
          <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
            <thead>
            <tr>
              <th class="hasinput"><input type="text" class="form-control" placeholder="Filter name" /></th>
              <th class="hasinput"><input type="text" class="form-control" placeholder="Filter url" /></th>
              <th class="hasinput" ></th>
            </tr>
            <tr>
              <th width="10%">Name</th>
              <th>Url</th>
              <th width="14%">Actions</th>
            </tr>
            </thead>
            <tbody id="sortable" data-url="/admin/backend_menus/ajax_update_position">
            <% @backend_menus.each_with_index do |backend_menu| %>
                <tr class='data' data-id="<%= backend_menu.id %>">
                  <td><%= backend_menu.name %></td>
                  <td><%= backend_menu.url %></td>
                  <td>
                    <center>
                      <%= link_to(edit_admin_backend_menu_path(backend_menu), 'escape' => false, 'class' => 'btn btn-sm btn-default') do%>
                          <i class="fa fa-edit" title="Edit"></i>
                      <% end %>
                      <%= link_to(admin_backend_menu_path(backend_menu), 'class' => 'btn btn-sm btn-default deleteLin', method: :delete, data: { confirm: 'Are you sure?' }) do %>
                          <i class="fa fa-trash-o" title="Delete"></i>
                      <% end %>
                    </center>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </article>
</div>

app/views/admin/backend_menus/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa fa-cog fa-fw "></i>
      <%= 'System' %>
      <span>&gt;
        <%=  link_to 'List of backend menus', admin_backend_menus_path %>
      </span>
    </h1>
  </div>
</div>
<div class="row">
  <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

    <div class="jarviswidget jarviswidget-sortable jarviswidget-color-darken" id="wid-id-4" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">

      <header role="heading">
        <span class="widget-icon">
            <i class="fa fa-edit"></i>
        </span>
        <h2><%= 'New Backend Menu'%></h2>
      </header>

      <div role="content">
        <div class="widget-body">

          <%= render 'form' %>

        </div>
      </div>

    </div>
  </article>
</div>