config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "devise/user/sessions", registrations: "devise/user/registrations", passwords: "devise/user/passwords"}

  root 'user/pages#welcome'

  namespace :admin do
    root 'pages#dashboard'

    resources :backend_menus do
      collection do
        post 'ajax_update_position'
      end
    end
    resources :users do
      collection do
        post 'assign_role'
      end
    end
  end

  devise_scope :user do
    get "admin/sign_in" => "devise/admin/sessions#new"
    get "admin/sign_up" => "devise/admin/registrations#new"
    get "admin/password/new" => "devise/admin/passwords#new"
    get "admin/password/edit" => "devise/admin/passwords#edit"
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  role                   :string(255)
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ActionController::Base.helpers.asset_path('default_user.png')
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  extend Enumerize
  enumerize :role, in: [:admin, :manage, :user], default: :user

  def update_check_password params
    params[:password].blank? ? self.update_without_password(params) : self.update(params)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :destroy, :update, :assign_role]

  def index
    if params[:query].present?
      @users = User.search params[:query], operator: "or", fields: [:email], order: {created_at: :desc}
    else
      @users = User.all.order("created_at DESC")
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = "User was successfully created."
        format.html { redirect_to admin_user_path(@user) }
      else
        flash.now[:danger] = @user.errors.full_messages
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update_check_password(user_params)
        flash[:success] = "User was successfully updated."
        format.html { redirect_to admin_user_path(@user) }
      else
        flash.now[:danger] = @user.errors.full_messages
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = "User was successfully destroyed."
      format.html { redirect_to admin_users_path }
    end
  end

  def assign_role
    if @user.update(role: params[:role])
      render json: {success: 'successfully'}
    else
      render json: {error: @user.errors.full_messages}
    end
  end

  private

  def set_user
    @user = User.find(params[:id]) rescue nil
    redirect_to admin_users_path, :flash => {danger: "User does not exist"} unless @user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar, :role)
  end

end

app/controllers/user/pages_controller.rb
class User::PagesController < UserController
  before_action :authenticate_user!

  def welcome
  end
end

app/controllers/user_controller.rb
class UserController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa fa-cog fa-fw "></i>
      <%= 'System' %>
        <span>&gt;
          <%=  link_to 'List of users', admin_users_path, 'data-turbolinks-track' => false %>
        </span>
    </h1>
  </div>
</div>
<div class="row">
  <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget jarviswidget-sortable jarviswidget-color-darken" id="wid-id-4" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">
      <header role="heading">
        <span class="widget-icon">
          <i class="fa fa-edit"></i>
        </span>
        <h2><%= user.new_record? ? 'New User' : 'Edit User'%></h2>
      </header>

      <!-- widget div-->
      <div role="content">
        <!-- widget content -->
        <div class="widget-body">
          <%= form_for([:admin, user], :html => {class: 'form-horizontal', id: 'smart-form-register'}) do |f| %>
            <div class="form-group">
              <label class="col-sm-2"></label>
              <div class="col-sm-8">
                <%= image_tag(@user.avatar , width: 80, id: 'privew_user_avatar') %>
              </div>
            </div>
            <div class="form-group">
              <label for="name" class="col-sm-2 control-label"><%= f.label :avatar %></label>
              <div class="col-sm-8">
                <%= f.file_field :avatar, class: 'form-control', accept: "image/x-png, image/gif, image/jpeg" %>
              </div>
            </div>
            <div class="form-group">
              <label for="name" class="col-sm-2 control-label"><%= f.label :email %></label>
              <div class="col-sm-8">
                <%= f.text_field :email, class: 'form-control', :required => true %>
              </div>
            </div>
            <% unless user.new_record? %>
              <div class="form-group">
                <p class="col-sm-8 col-md-offset-2">Leave password blank if dont want to change</p>
              </div>
            <% end %>

            <div class="form-group">
              <label for="information" class="col-sm-2 control-label"><%= f.label :password %></label>
              <div class="col-sm-8">
                <%= f.password_field :password, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <label for="information" class="col-sm-2 control-label"><%= f.label :password_confirmation %></label>
              <div class="col-sm-8">
                <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <label for="name" class="col-sm-2 control-label"><%= f.label :role %></label>
              <div class="col-sm-8">
                <%= f.select :role, User.role.options, {}, {class: 'form-control'} %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-8">
                <%= f.submit :class => "btn btn-primary"%>
              </div>
            </div>
          <% end %>
        </div>
        <!-- end widget content -->
      </div>
      <!-- end widget div -->
    </div>
    <!-- end widget -->
  </article>
</div>

app/views/admin/users/edit.html.erb
<%= render partial: "form", locals: { user: @user} %>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark"><i class="fa-fw fa fa-home"></i> Dashboard <span>> List of users</span></h1>
  </div>
  <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
    <ul id="sparks" class="">
      <li class="sparks-info">
        <%= link_to 'Add new user', new_admin_user_url, :class => 'btn btn-primary'%>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="true">
      <header>
        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
        <h2><%= 'List of Users' %></h2>
      </header>
      <div>
        <div class="jarviswidget-editbox"></div>

        <div class="widget-body">
          <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
            <thead>
              <tr>
                <th class="hasinput"></th>
                <th class="hasinput"></th>
                <th class="hasinput"><input type="text" class="form-control" placeholder="Filter email" /></th>
                <th class="hasinput"></th>
                <th class="hasinput" ></th>
              </tr>
              <tr>
                <th class="col-md-1">ID</th>
                <th class="col-md-2">Avatar</th>
                <th class="col-md-4">Email</th>
                <th class="col-md-2">Role</th>
                <th class="col-md-3">Actions</th>
              </tr>
            </thead>
            <tbody>
            <% @users.each_with_index do |user, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><center><%= image_tag user.avatar.url(:thumb), width: 60 if user.avatar.present? %></center></td>
                  <td><%= user.email %></td>
                  <td><%= select_tag 'role', options_for_select(User.role.values, user.role), class: 'form-control user_role', 'data-id' => user.id %></td>
                  <td>
                    <center>
                      <%= link_to(admin_user_path(user), 'data-no-turbolink' => true, 'escape' => false, 'class' => 'btn btn-sm btn-default') do %>
                          <i class="fa fa-eye" title="Show" class="btn btn-sm btn-default" escape="false"></i>
                      <% end %>
                      <%= link_to(edit_admin_user_path(user), 'escape' => false, 'class' => 'btn btn-sm btn-default') do%>
                          <i class="fa fa-edit" title="Edit"></i>
                      <% end %>
                      <%= link_to(admin_user_path(user), 'class' => 'btn btn-sm btn-default deleteLin', method: :delete, data: { confirm: 'Are you sure?' }) do %>
                          <i class="fa fa-trash-o" title="Delete"></i>
                      <% end %>
                  </center>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </article>
</div>

app/views/admin/users/new.html.erb
<%= render partial: "form", locals: { user: @user} %>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <i class="fa fa-cog fa-fw "></i>
      <%= 'System' %>
        <span>&gt;
          <%= link_to 'List of users', admin_users_path %>
        </span>
    </h1>
  </div>
</div>
<div class="row">
  <article class="col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">

    <div class="jarviswidget jarviswidget-sortable jarviswidget-color-darken" id="wid-id-4" data-widget-editbutton="false" data-widget-custombutton="false" role="widget" style="">

      <header role="heading">
        <span class="widget-icon">
            <i class="fa fa-user"></i>
        </span>
        <h2>User View</h2>
      </header>

      <div role="content">
        <!-- widget content -->
        <div class="widget-body">
          <fieldset>
            <table id="user" class="table table-bordered table-striped" style="clear: both">
              <tbody>
              <tr>
                <td style="width:35%;">Image</td>
                <td style="width:65%"><%= image_tag(@user.avatar, width: 80) %></td>
              </tr>
              <tr>
                <td style="width:35%;">Email</td>
                <td style="width:65%"><%= @user.email %></td>
              </tr>
              <tr>
                <td style="width:35%;">Role</td>
                <td style="width:65%"><%= @user.role %></td>
              </tr>
              </tbody>
            </table>
          </fieldset>

          <div class="form-actions">
            <div class="row">
              <div class="col-md-12">
                <%= link_to 'Back', admin_users_url, :class => 'btn btn-default'%>
                <%= link_to 'Edit', edit_admin_user_path(@user), :class => 'btn btn-primary'%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </article>
</div>